# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-21 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20181021_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.UUIDField(default=b'd13e0214-5627-4e06-b896-eb1e62f2432e', editable=False, primary_key=True, serialize=False),
        ),
    ]
