# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-10-21 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_todo_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='complete',
        ),
    ]
